[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
ureq = { workspace = true }
anyhow = { workspace = true }
lzma-rust2 = { workspace = true }
