[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
futures-core = { workspace = true }
http-body = { workspace = true }
lazy_static = { workspace = true }
opendal = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tower-http = { workspace = true }
