[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
lzma-rust2 = { workspace = true }
opendal = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
